// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBsVu8NAKs9F8wvi3UKUagNRADV-Tv2E',
    appId: '1:486912036941:web:1417c6baedc77290db4c04',
    messagingSenderId: '486912036941',
    projectId: 'licenta-animeet',
    authDomain: 'licenta-animeet.firebaseapp.com',
    storageBucket: 'licenta-animeet.appspot.com',
    measurementId: 'G-WFJMJER574',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB90wRAOeti98WCj2xLAq1Cg8Q581lu-e4',
    appId: '1:486912036941:android:fe79584366a5c9cfdb4c04',
    messagingSenderId: '486912036941',
    projectId: 'licenta-animeet',
    storageBucket: 'licenta-animeet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaqKGAC0xMidD5XZw2KCrKBSEtheq4I8',
    appId: '1:486912036941:ios:c553365fe4ae7a68db4c04',
    messagingSenderId: '486912036941',
    projectId: 'licenta-animeet',
    storageBucket: 'licenta-animeet.appspot.com',
    androidClientId: '486912036941-rq55spsvbbr6fbeuspr465ucpv3cds72.apps.googleusercontent.com',
    iosClientId: '486912036941-5tetaivcs33b362pi6jp6sc8f8idoq7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ani_meet',
  );
}
